### ISSUE TITLE
Remove rude examples banner as well

### ISSUE THREAD

**Issue by MRGRD56** [MRGRD56/reverso-context-unblocker#1]
Remove rude examples banner as well

```css
body.rude.rude-lock #examples-content .example {
    -webkit-filter: blur(3px);
    filter: blur(3px);
}
```

on
#OPENSUBTITLES-2016.EN-RU_12443733
